import type {
  BillingDashboardData,
  BillingReportData,
  Customer,
  InventoryAnalyticsData,
  InventoryDashboardData,
  Invoice,
  Order,
  Payment,
  Product,
  PurchaseOrder,
  StockMovement,
  Subscription,
  Supplier,
} from "@jewellery-retail/types";
import { calculateStockValue } from "@jewellery-retail/utils";

export const mockInvoices: Invoice[] = [
  {
    id: "inv-001",
    invoiceNumber: "MMJ-2401",
    customerId: "cust-001",
    customerName: "Aarav Shah",
    amount: 182000,
    status: "paid",
    issuedAt: "2026-03-01",
    dueDate: "2026-03-05",
    paymentMethod: "UPI",
    items: 3,
    downloadUrl: "#",
  },
  {
    id: "inv-002",
    invoiceNumber: "MMJ-2402",
    customerId: "cust-002",
    customerName: "Ishita Mehta",
    amount: 94000,
    status: "pending",
    issuedAt: "2026-03-04",
    dueDate: "2026-03-10",
    paymentMethod: "Card",
    items: 2,
    downloadUrl: "#",
  },
  {
    id: "inv-003",
    invoiceNumber: "MMJ-2403",
    customerId: "cust-003",
    customerName: "Vivaan Patel",
    amount: 265000,
    status: "paid",
    issuedAt: "2026-03-06",
    dueDate: "2026-03-06",
    paymentMethod: "Bank",
    items: 4,
    downloadUrl: "#",
  },
  {
    id: "inv-004",
    invoiceNumber: "MMJ-2404",
    customerId: "cust-004",
    customerName: "Siya Kapoor",
    amount: 76000,
    status: "overdue",
    issuedAt: "2026-02-22",
    dueDate: "2026-02-28",
    paymentMethod: "Cash",
    items: 1,
    downloadUrl: "#",
  },
  {
    id: "inv-005",
    invoiceNumber: "MMJ-2405",
    customerId: "cust-005",
    customerName: "Kabir Jain",
    amount: 129000,
    status: "draft",
    issuedAt: "2026-03-08",
    dueDate: "2026-03-14",
    paymentMethod: "UPI",
    items: 2,
    downloadUrl: "#",
  },
];

export const mockPayments: Payment[] = [
  {
    id: "pay-001",
    invoiceNumber: "MMJ-2401",
    customerName: "Aarav Shah",
    amount: 182000,
    method: "upi",
    status: "paid",
    createdAt: "2026-03-01",
    reference: "UPI-221845",
  },
  {
    id: "pay-002",
    invoiceNumber: "MMJ-2402",
    customerName: "Ishita Mehta",
    amount: 40000,
    method: "card",
    status: "pending",
    createdAt: "2026-03-04",
    reference: "CARD-99214",
  },
  {
    id: "pay-003",
    invoiceNumber: "MMJ-2403",
    customerName: "Vivaan Patel",
    amount: 265000,
    method: "bank",
    status: "paid",
    createdAt: "2026-03-06",
    reference: "NEFT-77891",
  },
  {
    id: "pay-004",
    invoiceNumber: "MMJ-2404",
    customerName: "Siya Kapoor",
    amount: 76000,
    method: "cash",
    status: "failed",
    createdAt: "2026-03-07",
    reference: "CASH-1049",
  },
  {
    id: "pay-005",
    invoiceNumber: "MMJ-2405",
    customerName: "Kabir Jain",
    amount: 62000,
    method: "upi",
    status: "paid",
    createdAt: "2026-03-09",
    reference: "UPI-30021",
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "cust-001",
    name: "Aarav Shah",
    email: "aarav@mmj.demo",
    phone: "+91 98765 41001",
    city: "Ahmedabad",
    segment: "VIP",
    totalSpend: 845000,
    outstandingBalance: 0,
    status: "active",
    lastPurchaseAt: "2026-03-01",
    purchaseHistory: [
      { id: "ph-1", invoiceNumber: "MMJ-2401", amount: 182000, date: "2026-03-01", status: "paid" },
      { id: "ph-2", invoiceNumber: "MMJ-2355", amount: 244000, date: "2026-02-12", status: "paid" },
    ],
  },
  {
    id: "cust-002",
    name: "Ishita Mehta",
    email: "ishita@mmj.demo",
    phone: "+91 98765 41002",
    city: "Surat",
    segment: "Loyal",
    totalSpend: 328000,
    outstandingBalance: 54000,
    status: "active",
    lastPurchaseAt: "2026-03-04",
    purchaseHistory: [
      { id: "ph-3", invoiceNumber: "MMJ-2402", amount: 94000, date: "2026-03-04", status: "pending" },
    ],
  },
  {
    id: "cust-003",
    name: "Vivaan Patel",
    email: "vivaan@mmj.demo",
    phone: "+91 98765 41003",
    city: "Mumbai",
    segment: "VIP",
    totalSpend: 960000,
    outstandingBalance: 0,
    status: "active",
    lastPurchaseAt: "2026-03-06",
    purchaseHistory: [
      { id: "ph-4", invoiceNumber: "MMJ-2403", amount: 265000, date: "2026-03-06", status: "paid" },
    ],
  },
  {
    id: "cust-004",
    name: "Siya Kapoor",
    email: "siya@mmj.demo",
    phone: "+91 98765 41004",
    city: "Pune",
    segment: "New",
    totalSpend: 76000,
    outstandingBalance: 76000,
    status: "active",
    lastPurchaseAt: "2026-02-22",
    purchaseHistory: [
      { id: "ph-5", invoiceNumber: "MMJ-2404", amount: 76000, date: "2026-02-22", status: "overdue" },
    ],
  },
  {
    id: "cust-005",
    name: "Kabir Jain",
    email: "kabir@mmj.demo",
    phone: "+91 98765 41005",
    city: "Jaipur",
    segment: "Loyal",
    totalSpend: 412000,
    outstandingBalance: 67000,
    status: "active",
    lastPurchaseAt: "2026-03-08",
    purchaseHistory: [
      { id: "ph-6", invoiceNumber: "MMJ-2405", amount: 129000, date: "2026-03-08", status: "draft" },
    ],
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: "sub-001",
    customerId: "cust-001",
    customerName: "Aarav Shah",
    plan: "Diamond Care",
    monthlyAmount: 12000,
    billingCycle: "monthly",
    renewsAt: "2026-04-01",
    status: "active",
    mrr: 12000,
  },
  {
    id: "sub-002",
    customerId: "cust-002",
    customerName: "Ishita Mehta",
    plan: "Gold Plus",
    monthlyAmount: 8000,
    billingCycle: "monthly",
    renewsAt: "2026-04-04",
    status: "trial",
    mrr: 8000,
  },
  {
    id: "sub-003",
    customerId: "cust-003",
    customerName: "Vivaan Patel",
    plan: "Diamond Care",
    monthlyAmount: 15000,
    billingCycle: "quarterly",
    renewsAt: "2026-05-10",
    status: "active",
    mrr: 15000,
  },
  {
    id: "sub-004",
    customerId: "cust-005",
    customerName: "Kabir Jain",
    plan: "Silver Save",
    monthlyAmount: 5000,
    billingCycle: "monthly",
    renewsAt: "2026-03-20",
    status: "past_due",
    mrr: 5000,
  },
];

export const mockProducts: Product[] = [
  {
    id: "prod-001",
    sku: "GLD-RNG-001",
    name: "Royal Gold Ring",
    category: "Rings",
    price: 38500,
    stock: 22,
    supplier: "Shree Bullion House",
    location: "Ahmedabad Vault",
    status: "active",
  },
  {
    id: "prod-002",
    sku: "GLD-CHN-010",
    name: "Heritage Chain",
    category: "Chains",
    price: 114000,
    stock: 7,
    supplier: "Zen Gold Works",
    location: "Mumbai Studio",
    status: "low",
  },
  {
    id: "prod-003",
    sku: "DMD-NEC-004",
    name: "Polki Diamond Necklace",
    category: "Necklaces",
    price: 246000,
    stock: 4,
    supplier: "Mira Gems",
    location: "Ahmedabad Vault",
    status: "low",
  },
  {
    id: "prod-004",
    sku: "SLV-BRC-008",
    name: "Silver Kada",
    category: "Bracelets",
    price: 14200,
    stock: 45,
    supplier: "Silverline Crafts",
    location: "Surat Store",
    status: "active",
  },
  {
    id: "prod-005",
    sku: "GLD-ERG-003",
    name: "Temple Earrings",
    category: "Earrings",
    price: 29200,
    stock: 0,
    supplier: "Zen Gold Works",
    location: "Ahmedabad Vault",
    status: "out_of_stock",
  },
  {
    id: "prod-006",
    sku: "DMD-RNG-021",
    name: "Solitaire Ring",
    category: "Rings",
    price: 175000,
    stock: 5,
    supplier: "Mira Gems",
    location: "Mumbai Studio",
    status: "low",
  },
];

export const mockStockMovements: StockMovement[] = [
  {
    id: "mov-001",
    productId: "prod-001",
    productName: "Royal Gold Ring",
    sku: "GLD-RNG-001",
    quantity: 12,
    type: "inbound",
    location: "Ahmedabad Vault",
    status: "completed",
    updatedAt: "2026-03-09",
  },
  {
    id: "mov-002",
    productId: "prod-002",
    productName: "Heritage Chain",
    sku: "GLD-CHN-010",
    quantity: 2,
    type: "outbound",
    location: "Mumbai Studio",
    status: "completed",
    updatedAt: "2026-03-08",
  },
  {
    id: "mov-003",
    productId: "prod-003",
    productName: "Polki Diamond Necklace",
    sku: "DMD-NEC-004",
    quantity: 1,
    type: "transfer",
    location: "Surat Store",
    status: "pending",
    updatedAt: "2026-03-08",
  },
  {
    id: "mov-004",
    productId: "prod-004",
    productName: "Silver Kada",
    sku: "SLV-BRC-008",
    quantity: 20,
    type: "inbound",
    location: "Surat Store",
    status: "completed",
    updatedAt: "2026-03-06",
  },
  {
    id: "mov-005",
    productId: "prod-006",
    productName: "Solitaire Ring",
    sku: "DMD-RNG-021",
    quantity: 1,
    type: "outbound",
    location: "Mumbai Studio",
    status: "completed",
    updatedAt: "2026-03-05",
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: "sup-001",
    name: "Shree Bullion House",
    contactPerson: "Rajesh Soni",
    email: "rajesh@bullion.demo",
    phone: "+91 98250 20001",
    city: "Ahmedabad",
    status: "active",
    supplierType: "gold",
    onTimeRate: 96,
    openOrders: 2,
    businessRegistrationNumber: "REG-GJ-2018-001",
    gstNumber: "27AABCU9603R1ZM",
    panNumber: "AABCU9603R",
    alternatePhone: "+91 98250 20009",
    website: "https://shreebullion.demo",
    state: "Gujarat",
    pincode: "380001",
    fullAddress: "12 Relief Road, Ahmedabad, Gujarat 380001",
    bankName: "State Bank of India",
    accountNumber: "****4521",
    ifscCode: "SBIN0001234",
    paymentTerms: "Net 30",
    creditLimit: 5000000,
    currency: "INR",
    metalTypes: ["Gold", "Silver"],
    itemCategories: ["Chain", "Bangle", "Ring"],
    leadTimeDays: 7,
    minimumOrderValue: 50000,
    notes: "Premium gold supplier for bulk orders.",
  },
  {
    id: "sup-002",
    name: "Zen Gold Works",
    contactPerson: "Nirav Shah",
    email: "nirav@zengold.demo",
    phone: "+91 98250 20002",
    city: "Rajkot",
    status: "active",
    supplierType: "gold",
    onTimeRate: 91,
    openOrders: 4,
    businessRegistrationNumber: "REG-GJ-2019-042",
    gstNumber: "24AABCZ1234K1Z5",
    panNumber: "AABCZ1234K",
    alternatePhone: "+91 98250 20008",
    website: "https://zengold.demo",
    state: "Gujarat",
    pincode: "360001",
    fullAddress: "5 Kalawad Road, Rajkot, Gujarat 360001",
    bankName: "HDFC Bank",
    accountNumber: "****7832",
    ifscCode: "HDFC0001234",
    paymentTerms: "Net 15",
    creditLimit: 3000000,
    currency: "INR",
    metalTypes: ["Gold", "Platinum"],
    itemCategories: ["Ring", "Necklace", "Earring"],
    leadTimeDays: 10,
    minimumOrderValue: 75000,
    notes: "Specialises in custom designs.",
  },
  {
    id: "sup-003",
    name: "Mira Gems",
    contactPerson: "Riddhi Kothari",
    email: "riddhi@miragems.demo",
    phone: "+91 98250 20003",
    city: "Mumbai",
    status: "active",
    supplierType: "diamond",
    onTimeRate: 89,
    openOrders: 3,
    businessRegistrationNumber: "REG-MH-2020-118",
    gstNumber: "27AABCM5678P1Z2",
    panNumber: "AABCM5678P",
    alternatePhone: "+91 98250 20007",
    website: "https://miragems.demo",
    state: "Maharashtra",
    pincode: "400001",
    fullAddress: "22 Zaveri Bazaar, Mumbai, Maharashtra 400001",
    bankName: "ICICI Bank",
    accountNumber: "****9012",
    ifscCode: "ICIC0001234",
    paymentTerms: "Net 30",
    creditLimit: 8000000,
    currency: "INR",
    metalTypes: ["Diamond", "Gold"],
    itemCategories: ["Ring", "Pendant", "Earring", "Bracelet"],
    leadTimeDays: 14,
    minimumOrderValue: 100000,
    notes: "Certified conflict-free diamonds.",
  },
  {
    id: "sup-004",
    name: "Silverline Crafts",
    contactPerson: "Ketan Doshi",
    email: "ketan@silverline.demo",
    phone: "+91 98250 20004",
    city: "Surat",
    status: "pending",
    supplierType: "silver",
    onTimeRate: 84,
    openOrders: 1,
    businessRegistrationNumber: "REG-GJ-2017-089",
    gstNumber: "24AABCS9012L1Z9",
    panNumber: "AABCS9012L",
    alternatePhone: "+91 98250 20006",
    website: "https://silverline.demo",
    state: "Gujarat",
    pincode: "395001",
    fullAddress: "8 Ring Road, Surat, Gujarat 395001",
    bankName: "Axis Bank",
    accountNumber: "****3456",
    ifscCode: "UTIB0001234",
    paymentTerms: "Net 45",
    creditLimit: 2000000,
    currency: "INR",
    metalTypes: ["Silver", "Stone"],
    itemCategories: ["Bangle", "Chain", "Pendant", "Other"],
    leadTimeDays: 12,
    minimumOrderValue: 25000,
    notes: "Silver and stone jewellery focus.",
  },
];

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: "po-001",
    poNumber: "PO-2301",
    supplierId: "sup-001",
    supplierName: "Shree Bullion House",
    total: 560000,
    status: "approved",
    expectedDate: "2026-03-16",
    createdAt: "2026-03-05",
    items: 8,
  },
  {
    id: "po-002",
    poNumber: "PO-2302",
    supplierId: "sup-003",
    supplierName: "Mira Gems",
    total: 880000,
    status: "in_transit",
    expectedDate: "2026-03-18",
    createdAt: "2026-03-07",
    items: 4,
  },
  {
    id: "po-003",
    poNumber: "PO-2303",
    supplierId: "sup-002",
    supplierName: "Zen Gold Works",
    total: 240000,
    status: "draft",
    expectedDate: "2026-03-21",
    createdAt: "2026-03-09",
    items: 5,
  },
  {
    id: "po-004",
    poNumber: "PO-2304",
    supplierId: "sup-004",
    supplierName: "Silverline Crafts",
    total: 124000,
    status: "received",
    expectedDate: "2026-03-11",
    createdAt: "2026-03-02",
    items: 11,
  },
];

export const mockOrders: Order[] = [
  {
    id: "ord-001",
    reference: "ORD-1001",
    customerName: "Aarav Shah",
    total: 182000,
    status: "completed",
    createdAt: "2026-03-01",
  },
  {
    id: "ord-002",
    reference: "ORD-1002",
    customerName: "Ishita Mehta",
    total: 94000,
    status: "processing",
    createdAt: "2026-03-04",
  },
  {
    id: "ord-003",
    reference: "ORD-1003",
    customerName: "Kabir Jain",
    total: 129000,
    status: "pending",
    createdAt: "2026-03-08",
  },
];

export const mockBillingDashboard: BillingDashboardData = {
  totalRevenue: 4620000,
  monthlyRevenue: 980000,
  pendingInvoices: mockInvoices.filter((invoice) => invoice.status === "pending" || invoice.status === "overdue").length,
  activeCustomers: mockCustomers.length,
  monthlyRevenueSeries: [
    { label: "Oct", value: 680000 },
    { label: "Nov", value: 720000 },
    { label: "Dec", value: 810000 },
    { label: "Jan", value: 790000 },
    { label: "Feb", value: 860000 },
    { label: "Mar", value: 980000 },
  ],
  customerGrowthSeries: [
    { label: "Oct", value: 120 },
    { label: "Nov", value: 138 },
    { label: "Dec", value: 149 },
    { label: "Jan", value: 162 },
    { label: "Feb", value: 176 },
    { label: "Mar", value: 194 },
  ],
  recentTransactions: mockPayments,
};

export const mockBillingReports: BillingReportData = {
  revenueSeries: mockBillingDashboard.monthlyRevenueSeries,
  customerGrowthSeries: mockBillingDashboard.customerGrowthSeries,
  planDistribution: [
    { name: "Diamond Care", value: 2 },
    { name: "Gold Plus", value: 1 },
    { name: "Silver Save", value: 1 },
  ],
};

export const mockInventoryDashboard: InventoryDashboardData = {
  totalProducts: mockProducts.length,
  lowStockItems: mockProducts.filter((product) => product.status === "low" || product.status === "out_of_stock").length,
  stockValue: calculateStockValue(mockProducts),
  openPurchaseOrders: mockPurchaseOrders.filter((order) => order.status !== "received").length,
  stockValueSeries: [
    { label: "Oct", value: 2900000 },
    { label: "Nov", value: 3020000 },
    { label: "Dec", value: 3180000 },
    { label: "Jan", value: 3300000 },
    { label: "Feb", value: 3410000 },
    { label: "Mar", value: 3520000 },
  ],
  recentStockUpdates: mockStockMovements,
  categoryBreakdown: [
    { name: "Rings", value: 27 },
    { name: "Chains", value: 16 },
    { name: "Necklaces", value: 11 },
    { name: "Bracelets", value: 19 },
  ],
};

export const mockInventoryAnalytics: InventoryAnalyticsData = {
  stockValuationSeries: mockInventoryDashboard.stockValueSeries,
  topSellingItems: [
    { name: "Royal Gold Ring", sold: 36, revenue: 1386000 },
    { name: "Heritage Chain", sold: 18, revenue: 2052000 },
    { name: "Solitaire Ring", sold: 10, revenue: 1750000 },
  ],
  lowInventoryAlerts: mockProducts.filter((product) => product.status !== "active"),
};
